### ISSUE TITLE
3 Issues with Newsroom page - one of the cards description missing, 4th card is exceeding the window in tablet view & display becomes off for the main section intermittently 

### ISSUE THREAD

**Issue by meejain** [sunstar-global/sunstar#21]
<img width="1396" alt="image" src="https://github.com/sunstar-global/sunstar/assets/37831850/58952603-5b3d-47cc-9382-ed6f45be83a2">

<img width="1109" alt="image" src="https://github.com/sunstar-global/sunstar/assets/37831850/18f5fbfc-0a90-4de2-9014-11b42b0e9652">

<img width="1385" alt="image" src="https://github.com/sunstar-global/sunstar/assets/37831850/b2bc0cb9-a7d3-4899-bf1b-00f278009bd1">

**Comment by ehrro** [comment]
Thank you @meejain for opening the issue.

**Comment by sdmcraft** [comment]
@ehrro , @meejain , can this be closed?
