### ISSUE TITLE
URL redirect with trailing forward slash / followed by hashtag #

### ISSUE THREAD

**Issue by ehrro** [sunstar-global/sunstar#23]
Check the last entry in the redirect.xlsx file.

![image](https://github.com/sunstar-global/sunstar/assets/1226479/27afadf9-abbc-4c6c-8b14-cb2313a061f1)

https://sunstarsuisse.sharepoint.com/:x:/r/sites/GlobalSunstarWebsite/_layouts/15/Doc.aspx?sourcedoc=%7B2DC29A4C-77B5-47D3-B331-47BFF3147997%7D&file=redirects.xlsx&action=default&mobileredirect=true

@sdmcraft

**Comment by bosschaert** [comment]
@ehrro while the linked PR transforms from a/b/c/#foo to a/b/c#foo the redirects.xlsx can't do a redirect from one anchor to another, see https://discord.com/channels/1131492224371277874/1197546382756683897/1197555947082629171
