### ISSUE TITLE
Add broken backlinks to redirect sheet

### ISSUE THREAD

**Issue by sdmcraft** [sunstar-global/sunstar#43]
[www.sunstar.com-broken-backlinks-subdomains__2024-02-14_11-44-10.csv](https://github.com/sunstar-global/sunstar/files/14280337/www.sunstar.com-broken-backlinks-subdomains__2024-02-14_11-44-10.csv)

**Comment by JiangLong2019** [comment]
Add Sunstar Engineering report.
[www.sunstar-engineering.com-broken-backlink__2024-02-14_17-09-12.csv](https://github.com/sunstar-global/sunstar/files/14295527/www.sunstar-engineering.com-broken-backlink__2024-02-14_17-09-12.csv)

**Comment by JiangLong2019** [comment]
Create sunstar.com redirect list.
[Redirection of Sunstar broken links.xlsx](https://github.com/sunstar-global/sunstar/files/14318980/Redirection.of.Sunstar.broken.links.xlsx)

**Comment by JiangLong2019** [comment]
Create sunstar-engineering.com redirect list.
[Redirection of Sunstar Engineering broken links.xlsx](https://github.com/sunstar-global/sunstar/files/14321496/Redirection.of.Sunstar.Engineering.broken.links.xlsx)

**Comment by JiangLong2019** [comment]
@sdmcraft please help to review the **Redirect destination** column of above 2 excel files, if all look good we can update it in prod.

**Comment by sdmcraft** [comment]
Thanks @JiangLong2019 . Looks good. @ehrro , fyi, we are adding all these redirects to ensure 301 redirect instead of 404 handler redirect.

**Comment by JiangLong2019** [comment]
@ehrro The 301 redirect has been published in prod, you can check on live site.

**Comment by JiangLong2019** [comment]
Created Sunstar Foundation redirect and updated in sharePoint as well.

[Redirection of Sunstar Foundation.xlsx](https://github.com/sunstar-global/sunstar/files/14328396/Redirection.of.Sunstar.Foundation.xlsx)

**Comment by ehrro** [comment]
Thank you guys much appreciated!

**Comment by meryllblanchet** [comment]
Hi team, just checking as I still see this issue open: have the redirects been setup successfully in production?
