### ISSUE TITLE
Fix robots.txt

### ISSUE THREAD

**Issue by sdmcraft** [sunstar-global/sunstar#50]
Rules prevent Robots from accessing parts of the page, preventing noindex logic in metadata to work
[Internal ref link](https://cq-dev.slack.com/archives/C05B53SRX7V/p1709573571023649) (may not work for everyone)

**Comment by bosschaert** [comment]
This is the same as https://github.com/hlxsites/sunstar-foundation/issues/138 - I'll take a look.
