### ISSUE TITLE
Add LinkedIn Pixel

### ISSUE THREAD

**Issue by ehrro** [sunstar-global/sunstar#54]
Team can someone help me to integrate the LinkedIn Pixel on Sunstar.com?

Here is code.

```javascript
<script type="text/javascript">
_linkedin_partner_id = "6858425";
window._linkedin_data_partner_ids = window._linkedin_data_partner_ids || [];
window._linkedin_data_partner_ids.push(_linkedin_partner_id);
</script><script type="text/javascript">
(function(l) {
if (!l){window.lintrk = function(a,b){window.lintrk.q.push([a,b])};
window.lintrk.q=[]}
var s = document.getElementsByTagName("script")[0];
var b = document.createElement("script");
b.type = "text/javascript";b.async = true;
b.src = "https://snap.licdn.com/li.lms-analytics/insight.min.js";
s.parentNode.insertBefore(b, s);})(window.lintrk);
</script>
<noscript>
<img height="1" width="1" style="display:none;" alt="" src="https://px.ads.linkedin.com/collect/?pid=6858425&fmt=gif" />
</noscript>
```

@bosschaert @sdmcraft @meejain @JiangLong2019 @jindaliiita

**Comment by JiangLong2019** [comment]
Hi @ehrro, do you have any requirements on where to insert the tag? Such as paste it in the head or above the closing HTML <body> tag in the global footer?

**Comment by ehrro** [comment]
Hello @JiangLong2019 you can add it at the end of the body tag. Make sure this is not loaded before the consent management script :) Thank you

**Comment by ehrro** [comment]
Hello @JiangLong2019,

I will just push the PR right now and we will check this later.

I added Linked in the Consent Management Console.

Thank you.
